### ISSUE TITLE
Problem with `sanitize-filename` package

### ISSUE THREAD

**Issue by zeitchef** [danieldiekmeier/textexpander-to-alfred3#10]
There appears to be an issue with one of your dependencies.

```
❯ te2a3 Composers.textexpander
/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/sanitize-filename/index.js:41
    .replace(illegalRe, replacement)
     ^

TypeError: Cannot read property 'replace' of undefined
    at sanitize (/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/sanitize-filename/index.js:41:6)
    at module.exports (/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/sanitize-filename/index.js:51:16)
    at transformSnippet (/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:29:15)
    at Array.map (<anonymous>)
    at textexpander2Alfred (/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:71:6)
    at /usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:55:21
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

**Comment by shravansundaram** [comment]
Is anyone able to fix this issue?

**Comment by danieldiekmeier** [comment]
This is probably not a problem with `sanitize-filename`, but with my bad code. I converted all my snippets over 3 years ago and haven't used TextExpander since, so I can't really do too much to help here.

But I looked at my code and there seemed to be a pretty obvious place where the bug probably originates, so I just published `v0.1.2` which _should_ fix it.

Can you update (using `npm i -g textexpander-to-alfred3@0.1.2`), and check if this fixed the problem?

**Comment by shravansundaram** [comment]
Doesn't seem like it fixed it. I tried to do some debugging and issue seems to be happening somewhere around here
parsedPlist.snippetsTE2
    .map(transformSnippet)
The transformSnippet is not getting the right value or undefined value which is causing sanitize to error.

**Comment by shravansundaram** [comment]
Also seems like the website doesn't work either. It returns an error after hitting covert

**Comment by danieldiekmeier** [comment]
I‘m sorry, but I won‘t be able to help you.

Obviously the website uses the exact same conversion script, so if the script doesn‘t work, then the website will also not work.

**Comment by matthewmcvickar** [comment]
@shravansundaram  This is fixed now!
