### ISSUE TITLE
"Label" in TextExpander Not Maintained

### ISSUE THREAD

**Issue by kenyarmosh** [danieldiekmeier/textexpander-to-alfred3#2]
Great script here. Just a heads up that the "Label" in TextExpander is not being maintained as far as I can see. It appears you're taking whatever the abbreviation was in TE and assigning it as the "Name" in Alfred. Labels from TE will be important to keep as Names in Alfred since you can search through snippets easily.

After import: https://www.dropbox.com/s/0plo21qw5qzyse4/Screenshot%202016-05-17%2020.48.24.png?dl=0
In TE: https://www.dropbox.com/s/9lr2a37mte71skk/Screenshot%202016-05-17%2020.48.55.png?dl=0

**Comment by danieldiekmeier** [comment]
That's a good point! I actually never used the label myself, that's why I didn't think of using it. Can you supply an sample TextExpander file with a few labels, so I can implement this? Would help a lot! (I actually don't have TextExpander installed anymore.)

**Comment by kenyarmosh** [comment]
@danieldiekmeier I figured you didn't. ;-) I actually just updating everything manually and then also removed TE. I had to do about 30 or so updates, which wasn't horrible but could be streamlined for others. So this was me just helping others in the future. Here's a couple of examples...

```
<dict>
            <key>abbreviation</key>
            <string>oas</string>
            <key>abbreviationMode</key>
            <integer>0</integer>
            <key>creationDate</key>
            <date>2014-01-27T14:18:33Z</date>
            <key>label</key>
            <string>savvy website</string>
            <key>modificationDate</key>
            <date>2014-01-27T14:18:59Z</date>
            <key>plainText</key>
            <string>http://savvyapps.com/</string>
            <key>snippetType</key>
            <integer>0</integer>
            <key>uuidString</key>
            <string>21CD1DA0-93DB-4FDB-A58F-9EDA835F95F0</string>
        </dict>

```

```
<dict>
            <key>abbreviation</key>
            <string>alink</string>
            <key>abbreviationMode</key>
            <integer>0</integer>
            <key>creationDate</key>
            <date>2011-07-28T03:36:37Z</date>
            <key>label</key>
            <string>Amazon Book Link</string>
            <key>modificationDate</key>
            <date>2011-07-28T03:37:52Z</date>
            <key>plainText</key>
            <string>http://amzn.to/dCWyI6</string>
            <key>snippetType</key>
            <integer>0</integer>
            <key>uuidString</key>
            <string>54E9F202-9F6B-4006-A355-A7B58E5A9836</string>
        </dict>
```

**Comment by yricimello** [comment]
Hi Daniel. I'm a newbie. 
I installed Node.js v6.2.0 Current, 
I installed your package : sudo npm install -g textexpander-to-alfred3, 
I got /usr/local/lib
└── textexpander-to-alfred3@0.0.3 
I  exported some TextExpander snippets
I executed textexpander-to-alfred3 /Users/admi/Desktop/te2alfred3/english.textexpander,
but got the error :
```
[xmldom error]	invalid document source 
@#[line:0,col:undefined]
/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/plist/lib/parse.js:45
  if (doc.documentElement.nodeName !== 'plist') {
         ^

TypeError: Cannot read property 'documentElement' of undefined
    at Object.parse (/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/plist/lib/parse.js:45:10)
    at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:27:25)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)


```
Here is the content of the file :

> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>groupInfo</key>
> 	<dict>
> 		<key>expandAfterMode</key>
> 		<integer>0</integer>
> 		<key>groupName</key>
> 		<string>english</string>
> 	</dict>
> 	<key>snippetsTE2</key>
> 	<array>
> 		<dict>
> 			<key>abbreviation</key>
> 			<string>bry</string>
> 			<key>abbreviationMode</key>
> 			<integer>0</integer>
> 			<key>creationDate</key>
> 			<date>2014-10-27T11:50:54Z</date>
> 			<key>label</key>
> 			<string></string>
> 			<key>modificationDate</key>
> 			<date>2014-10-27T11:52:07Z</date>
> 			<key>plainText</key>
> 			<string>Best Regards
> 
> Yves</string>
> 			<key>snippetType</key>
> 			<integer>0</integer>
> 			<key>uuidString</key>
> 			<string>63A4CBD1-E87C-471D-BCC4-01F1B869FAED</string>
> 		</dict>
> 		<dict>
> 			<key>abbreviation</key>
> 			<string>ybr</string>
> 			<key>abbreviationMode</key>
> 			<integer>0</integer>
> 			<key>creationDate</key>
> 			<date>2013-04-11T08:40:50Z</date>
> 			<key>label</key>
> 			<string></string>
> 			<key>modificationDate</key>
> 			<date>2013-07-23T16:16:56Z</date>
> 			<key>plainText</key>
> 			<string>Best regards,
> 
> Yves</string>
> 			<key>snippetType</key>
> 			<integer>0</integer>
> 			<key>uuidString</key>
> 			<string>EFBEC48F-9FB6-4518-A8DD-9567A2C9D9EA</string>
> 		</dict>
> 	</array>
> </dict>
> </plist>

Best Regards

Yves

**Comment by danieldiekmeier** [comment]
@yricimello Hey Yves, can you please add a new issue, and maybe create a [Gist](https://gist.github.com/) for your TextExpander file? (As you can see in your comment, most of the content got stripped out).

**Comment by danieldiekmeier** [comment]
Thanks for the help, this will be released shortly. (Even though you don't need it anymore. 💃 )
