### ISSUE TITLE
Information for newbies

### ISSUE THREAD

**Issue by scottmcdaniel** [danieldiekmeier/textexpander-to-alfred3#3]
Hi Daniel, can this (or something like it) be added to the readme? Might save some folks some time.
- The script requires node.js from https://nodejs.org/en/
  -- After installing the package, open a Terminal window, and type the following command (you will be prompted for an admin users password - usually it's your normal password unless you are on a managed system, i.e. WORK): sudo npm install -g textexpander-to-alfred3

**Comment by danieldiekmeier** [comment]
Hey Scott, thanks for the suggestion! I actually just released this tool as a web app: http://alfred.danieldiekmeier.de/

This makes it way easier to use, so even newbies should have no problem. I guess that's better than explaining Node to everybody. :D
