### ISSUE TITLE
xmldom error

### ISSUE THREAD

**Issue by polomatt** [danieldiekmeier/textexpander-to-alfred3#4]
I followed that tutorial :
http://www.alfredforum.com/topic/8883-import-textexpander-snippets-into-alfred-v3/
but I got an error :

```
textexpander-to-alfred3 english.textexpander
[xmldom error]  invalid document source 
@#[line:0,col:undefined]
/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/plist/lib/parse.js:45
  if (doc.documentElement.nodeName !== 'plist') {
         ^

TypeError: Cannot read property 'documentElement' of undefined
    at Object.parse (/usr/local/lib/node_modules/textexpander-to-alfred3/node_modules/plist/lib/parse.js:45:10)
    at ReadFileContext.fs.readFile [as callback] (/usr/local/lib/node_modules/textexpander-to-alfred3/textexpander-to-alfred3.js:27:25)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
pro:textexpander-to-alfred3-master admi$ 
```

I tried to make a Gist (Im a newbie...)
[fc608c7ef257826239ae2ffe6117f451-d873e389a92818c6b177b0a3d75dd256edffaafc.zip](https://github.com/danieldiekmeier/textexpander-to-alfred3/files/273176/fc608c7ef257826239ae2ffe6117f451-d873e389a92818c6b177b0a3d75dd256edffaafc.zip)

Hope it helps.

Best Regards

Yves

**Comment by danieldiekmeier** [comment]
Hm, that's really weird. I just tried your file, and for me, it works:

```
~/d/n/textexpander-to-alfred3> textexpander-to-alfred3 english.textexpander
Wrote file /Users/Daniel/dev/node/textexpander-to-alfred3/english.alfredsnippets
```

Can you try to download the latest release (I released it a few minutes ago, you just have to do `npm install -g textexpander-to-alfred3` again to get it) and try it again?

**Comment by danieldiekmeier** [comment]
Hey Yves, I just released this tool as a web app: http://alfred.danieldiekmeier.de/

Can you try it there? Maybe that solves your problem.

**Comment by polomatt** [comment]
I did that. Its work fine now. 

Thank you very much, for the tool, and for your help.

**Comment by polomatt** [comment]
I used the app too. Fine.

Much more convivial for the rest of us.

Thanks again, Daniel.
