### ISSUE TITLE
Convert Textexpander's spaces in Alfred 3's spaces. 

### ISSUE THREAD

**Issue by politicus** [danieldiekmeier/textexpander-to-alfred3#5]
Textexpander allows to add one or more spaces by adding "%|". 

After the conversion, they do expand as "%|".

Would be great if they were converted in Alfred'3 spaces. 

Thanks.

**Comment by danieldiekmeier** [comment]
@politicus According to this support article, `%|` does place the cursor at that position after expansion, and does not create _one or more spaces_: https://textexpander.com/entry/what-other-special-codes-can-be-used-in-textexpander-touch-snippets/

This behaviour is (at the moment) not supported by Alfred 3. The best way to add a space is probably by just using a `" "` space character. There are several other special codes in TextExpander, that Alfred doesn't implement and that this project does therefore not convert. I advise to convert them manually.

**Comment by politicus** [comment]
Thank you! 

It means I will have to convert a lot of snippets ;-)
