### ISSUE TITLE
Doesn't handle wildcards/multiple inputs

### ISSUE THREAD

**Issue by NuclearMonster** [danieldiekmeier/textexpander-to-alfred3#6]
If you run te2a3 with a \* it only processes the first .textexpander file

**Comment by danieldiekmeier** [comment]
That's true, but it's not something I plan on changing, because it's not really worth the effort, sorry.

You could try to use a bash loop to convert each file:

```
for i in *; do te2a3 "$i"; done
```

(Adapted from http://stackoverflow.com/questions/10523415/bash-script-to-execute-command-on-all-files-in-directory)
