### ISSUE TITLE
Also convert date/time macros from TE to Alfred

### ISSUE THREAD

**Issue by jk** [danieldiekmeier/textexpander-to-alfred3#8]
Like in Issue https://github.com/danieldiekmeier/textexpander-to-alfred3/issues/1 it would be great if we can convert snippets which expanded date/time macros like:

    %Y-%m-%d

to 

    {date:yyyy-MM-dd}

Those resources can help with that:
* [Alfred: Using Dynamic Placeholders in Clipboard Snippets](https://www.alfredapp.com/help/features/clipboard/dynamic-placeholders/)
* [NSDateFormatter date formatting table](http://waracle.net/iphone-nsdateformatter-date-formatting-table/)

Sadly I'm not proficient in Node.js (tried several times, it's not my style) so I can not make a PR. Hope my tiny google research helps to tackle the issue.

**Comment by danieldiekmeier** [comment]
Even more useful would be a complete mapping of TextExpander variables to Alfred variables, like

```
$Y: yyyy
$m: MM
$d: dd
```

and so on. If you can provide that, I'll gladly put it into the tool. I converted all my snippets 7 months ago, so I don't really plan on spending too much time on this, sorry. :D Thanks though!

**Comment by danieldiekmeier** [comment]
I'll close this now, there doesn't seem to be much interest in this.
