### ISSUE TITLE
site upload not working

### ISSUE THREAD

**Issue by Critter** [danieldiekmeier/textexpander-to-alfred3#9]
Hey.. not sure if you are still supporting the online version, but it throws an error when you attempt to upload.. just letting you know..

**Comment by danieldiekmeier** [comment]
I'm not really supporting this anymore, sorry. I think there were some errors with some edge cases from the start, but nobody ever bothered to submit a file that produces an error, so there's not much I can do.

**Comment by matthewmcvickar** [comment]
@Critter  This is fixed now!
